version: '3.2'
services:
  gateway:
    container_name: gatewayService
    image: john/final667
    build: .
    ports:
      - '3004:3004'
    command: ['node', './services/gateway.js']
    depends_on: ['redisServer', 'kafka']
    environment:
      - NODE_ENV=prod
      - WEBSOCKET_HOST=websocket
      - WEBSOCKET_PORT=3027
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  fileServer:
    container_name: fileServer
    image: john/final667
    build: .
    command: ['node', './services/fileServer.js']
    depends_on: ['redisServer', 'kafka']
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  register:
    container_name: registerServer
    image: john/final667
    build: .
    command: ['node', './services/registerServer.js']
    depends_on: ['redisServer', 'kafka']
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  user:
    container_name: userServer
    image: john/final667
    build: .
    command: ['node', './services/userService.js']
    depends_on: ['redisServer', 'kafka']
    environment:
      - REDISHOST=redisServer
      - DOMAIN=user
      - NODE_ENV=prod
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  auth:
    container_name: authService
    image: john/final667
    build: .
    command: ['node', './services/authService.js']
    depends_on: ['redisServer', 'kafka']
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  review:
    container_name: reviewService
    image: john/final667
    build: .
    command: ['node', './services/reviewService.js']
    depends_on: ['redisServer', 'kafka']
    environment:
      - REDISHOST=redisServer
      - NODE_ENV=prod
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  restaurant:
    container_name: restaurantService
    image: john/final667
    environment:
      - REDISHOST=redisServer
      - NODE_ENV=prod
    depends_on: ['redisServer', 'kafka']
    command: ['node', './services/restaurantServer.js']
    build: .
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  websocket:
    container_name: websocketService
    image: john/final667
    depends_on: ['redisServer', 'kafka']
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - REDISHOST=redisServer
      - NODE_ENV=prod
    build: .
    command: ['node', './services/websocket.js']
  restaurantConsumer:
    container_name: restaurantConsumerService
    image: john/final667
    environment:
      - REDISHOST=redisServer
      - NODE_ENV=prod
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    build: .
    command: ['node', './services/restaurantConsumer.js']
  redisServer:
    image: redis
    container_name: redisCache
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: '9092'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
